// <auto-generated />
using System;
using Checklist.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Checklist.Infra.Migrations
{
    [DbContext(typeof(RDbContext))]
    partial class RDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CheckList.Domain.CheckListBody", b =>
                {
                    b.Property<int>("CheckListBodyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckListBodyId"));

                    b.Property<DateTime?>("DataFimExecucao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicioExecucao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExecutorId")
                        .HasColumnType("int");

                    b.HasKey("CheckListBodyId");

                    b.HasIndex("ExecutorId");

                    b.ToTable("CheckListBody");
                });

            modelBuilder.Entity("CheckList.Domain.CheckListItem", b =>
                {
                    b.Property<int>("CheckListItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckListItemId"));

                    b.Property<int>("CheckListBodyId")
                        .HasColumnType("int");

                    b.Property<int>("PerguntaId")
                        .HasColumnType("int");

                    b.HasKey("CheckListItemId");

                    b.HasIndex("CheckListBodyId");

                    b.HasIndex("PerguntaId");

                    b.ToTable("CheckListItem");
                });

            modelBuilder.Entity("CheckList.Domain.Executor", b =>
                {
                    b.Property<int>("ExecutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExecutorId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExecutorId");

                    b.ToTable("Executor");
                });

            modelBuilder.Entity("CheckList.Domain.Pergunta", b =>
                {
                    b.Property<int>("PerguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerguntaId"));

                    b.Property<string>("Parametro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Questao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PerguntaId");

                    b.ToTable("Pergunta");
                });

            modelBuilder.Entity("CheckList.Domain.CheckListBody", b =>
                {
                    b.HasOne("CheckList.Domain.Executor", "Executor")
                        .WithMany()
                        .HasForeignKey("ExecutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Executor");
                });

            modelBuilder.Entity("CheckList.Domain.CheckListItem", b =>
                {
                    b.HasOne("CheckList.Domain.CheckListBody", "CheckListBody")
                        .WithMany()
                        .HasForeignKey("CheckListBodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheckList.Domain.Pergunta", "Pergunta")
                        .WithMany()
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckListBody");

                    b.Navigation("Pergunta");
                });
#pragma warning restore 612, 618
        }
    }
}
